# This is a basic workflow to help you get started with Actions

name: "release"

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
    tags:
      - "latest"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: "Build"
        run: |
          sh ./build.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            *.zip
